//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Taxi
{
    using System;
    using System.Collections.Generic;
    
    public partial class ADDROBJ03
    {
        public Nullable<double> ACTSTATUS { get; set; }
        public string AOGUID { get; set; }
        public string AOID { get; set; }
        public Nullable<double> AOLEVEL { get; set; }
        public string AREACODE { get; set; }
        public string AUTOCODE { get; set; }
        public Nullable<double> CENTSTATUS { get; set; }
        public string CITYCODE { get; set; }
        public string CODE { get; set; }
        public Nullable<double> CURRSTATUS { get; set; }
        public Nullable<System.DateTime> ENDDATE { get; set; }
        public string FORMALNAME { get; set; }
        public string IFNSFL { get; set; }
        public string IFNSUL { get; set; }
        public string NEXTID { get; set; }
        public string OFFNAME { get; set; }
        public string OKATO { get; set; }
        public string OKTMO { get; set; }
        public Nullable<double> OPERSTATUS { get; set; }
        public string PARENTGUID { get; set; }
        public string PLACECODE { get; set; }
        public string PLAINCODE { get; set; }
        public string POSTALCODE { get; set; }
        public string PREVID { get; set; }
        public string REGIONCODE { get; set; }
        public string SHORTNAME { get; set; }
        public Nullable<System.DateTime> STARTDATE { get; set; }
        public string STREETCODE { get; set; }
        public string TERRIFNSFL { get; set; }
        public string TERRIFNSUL { get; set; }
        public Nullable<System.DateTime> UPDATEDATE { get; set; }
        public string CTARCODE { get; set; }
        public string EXTRCODE { get; set; }
        public string SEXTCODE { get; set; }
        public Nullable<double> LIVESTATUS { get; set; }
        public string NORMDOC { get; set; }
    }
}
