//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Taxi
{
    using System;
    using System.Collections.Generic;
    
    public partial class HOUSE61
    {
        public string AOGUID { get; set; }
        public string BUILDNUM { get; set; }
        public Nullable<System.DateTime> ENDDATE { get; set; }
        public Nullable<double> ESTSTATUS { get; set; }
        public string HOUSEGUID { get; set; }
        public string HOUSEID { get; set; }
        public string HOUSENUM { get; set; }
        public Nullable<double> STATSTATUS { get; set; }
        public string IFNSFL { get; set; }
        public string IFNSUL { get; set; }
        public string OKATO { get; set; }
        public string OKTMO { get; set; }
        public string POSTALCODE { get; set; }
        public Nullable<System.DateTime> STARTDATE { get; set; }
        public string STRUCNUM { get; set; }
        public Nullable<double> STRSTATUS { get; set; }
        public string TERRIFNSFL { get; set; }
        public string TERRIFNSUL { get; set; }
        public Nullable<System.DateTime> UPDATEDATE { get; set; }
        public string NORMDOC { get; set; }
        public Nullable<double> COUNTER { get; set; }
    }
}
