//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Taxi
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class taxi : DbContext
    {
        public taxi()
            : base("name=taxi")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ADDROBJ> ADDROBJ { get; set; }
        public virtual DbSet<ADDROBJ01> ADDROBJ01 { get; set; }
        public virtual DbSet<ADDROBJ02> ADDROBJ02 { get; set; }
        public virtual DbSet<ADDROBJ03> ADDROBJ03 { get; set; }
        public virtual DbSet<ADDROBJ04> ADDROBJ04 { get; set; }
        public virtual DbSet<ADDROBJ05> ADDROBJ05 { get; set; }
        public virtual DbSet<ADDROBJ06> ADDROBJ06 { get; set; }
        public virtual DbSet<ADDROBJ07> ADDROBJ07 { get; set; }
        public virtual DbSet<ADDROBJ08> ADDROBJ08 { get; set; }
        public virtual DbSet<ADDROBJ09> ADDROBJ09 { get; set; }
        public virtual DbSet<ADDROBJ10> ADDROBJ10 { get; set; }
        public virtual DbSet<ADDROBJ11> ADDROBJ11 { get; set; }
        public virtual DbSet<ADDROBJ12> ADDROBJ12 { get; set; }
        public virtual DbSet<ADDROBJ13> ADDROBJ13 { get; set; }
        public virtual DbSet<ADDROBJ14> ADDROBJ14 { get; set; }
        public virtual DbSet<ADDROBJ15> ADDROBJ15 { get; set; }
        public virtual DbSet<ADDROBJ16> ADDROBJ16 { get; set; }
        public virtual DbSet<ADDROBJ17> ADDROBJ17 { get; set; }
        public virtual DbSet<ADDROBJ18> ADDROBJ18 { get; set; }
        public virtual DbSet<ADDROBJ19> ADDROBJ19 { get; set; }
        public virtual DbSet<ADDROBJ20> ADDROBJ20 { get; set; }
        public virtual DbSet<ADDROBJ21> ADDROBJ21 { get; set; }
        public virtual DbSet<ADDROBJ22> ADDROBJ22 { get; set; }
        public virtual DbSet<ADDROBJ23> ADDROBJ23 { get; set; }
        public virtual DbSet<ADDROBJ24> ADDROBJ24 { get; set; }
        public virtual DbSet<ADDROBJ25> ADDROBJ25 { get; set; }
        public virtual DbSet<ADDROBJ26> ADDROBJ26 { get; set; }
        public virtual DbSet<ADDROBJ27> ADDROBJ27 { get; set; }
        public virtual DbSet<ADDROBJ28> ADDROBJ28 { get; set; }
        public virtual DbSet<ADDROBJ29> ADDROBJ29 { get; set; }
        public virtual DbSet<ADDROBJ30> ADDROBJ30 { get; set; }
        public virtual DbSet<ADDROBJ31> ADDROBJ31 { get; set; }
        public virtual DbSet<ADDROBJ32> ADDROBJ32 { get; set; }
        public virtual DbSet<ADDROBJ33> ADDROBJ33 { get; set; }
        public virtual DbSet<ADDROBJ34> ADDROBJ34 { get; set; }
        public virtual DbSet<ADDROBJ35> ADDROBJ35 { get; set; }
        public virtual DbSet<ADDROBJ36> ADDROBJ36 { get; set; }
        public virtual DbSet<ADDROBJ37> ADDROBJ37 { get; set; }
        public virtual DbSet<ADDROBJ38> ADDROBJ38 { get; set; }
        public virtual DbSet<ADDROBJ39> ADDROBJ39 { get; set; }
        public virtual DbSet<ADDROBJ40> ADDROBJ40 { get; set; }
        public virtual DbSet<ADDROBJ41> ADDROBJ41 { get; set; }
        public virtual DbSet<ADDROBJ42> ADDROBJ42 { get; set; }
        public virtual DbSet<ADDROBJ43> ADDROBJ43 { get; set; }
        public virtual DbSet<ADDROBJ44> ADDROBJ44 { get; set; }
        public virtual DbSet<ADDROBJ45> ADDROBJ45 { get; set; }
        public virtual DbSet<ADDROBJ46> ADDROBJ46 { get; set; }
        public virtual DbSet<ADDROBJ47> ADDROBJ47 { get; set; }
        public virtual DbSet<ADDROBJ48> ADDROBJ48 { get; set; }
        public virtual DbSet<ADDROBJ49> ADDROBJ49 { get; set; }
        public virtual DbSet<ADDROBJ50> ADDROBJ50 { get; set; }
        public virtual DbSet<ADDROBJ51> ADDROBJ51 { get; set; }
        public virtual DbSet<ADDROBJ52> ADDROBJ52 { get; set; }
        public virtual DbSet<ADDROBJ53> ADDROBJ53 { get; set; }
        public virtual DbSet<ADDROBJ54> ADDROBJ54 { get; set; }
        public virtual DbSet<ADDROBJ55> ADDROBJ55 { get; set; }
        public virtual DbSet<ADDROBJ56> ADDROBJ56 { get; set; }
        public virtual DbSet<ADDROBJ57> ADDROBJ57 { get; set; }
        public virtual DbSet<ADDROBJ58> ADDROBJ58 { get; set; }
        public virtual DbSet<ADDROBJ59> ADDROBJ59 { get; set; }
        public virtual DbSet<ADDROBJ60> ADDROBJ60 { get; set; }
        public virtual DbSet<ADDROBJ61> ADDROBJ61 { get; set; }
        public virtual DbSet<ADDROBJ62> ADDROBJ62 { get; set; }
        public virtual DbSet<ADDROBJ63> ADDROBJ63 { get; set; }
        public virtual DbSet<ADDROBJ64> ADDROBJ64 { get; set; }
        public virtual DbSet<ADDROBJ65> ADDROBJ65 { get; set; }
        public virtual DbSet<ADDROBJ66> ADDROBJ66 { get; set; }
        public virtual DbSet<ADDROBJ67> ADDROBJ67 { get; set; }
        public virtual DbSet<ADDROBJ68> ADDROBJ68 { get; set; }
        public virtual DbSet<ADDROBJ69> ADDROBJ69 { get; set; }
        public virtual DbSet<ADDROBJ70> ADDROBJ70 { get; set; }
        public virtual DbSet<ADDROBJ71> ADDROBJ71 { get; set; }
        public virtual DbSet<ADDROBJ72> ADDROBJ72 { get; set; }
        public virtual DbSet<ADDROBJ73> ADDROBJ73 { get; set; }
        public virtual DbSet<ADDROBJ74> ADDROBJ74 { get; set; }
        public virtual DbSet<ADDROBJ75> ADDROBJ75 { get; set; }
        public virtual DbSet<ADDROBJ76> ADDROBJ76 { get; set; }
        public virtual DbSet<ADDROBJ77> ADDROBJ77 { get; set; }
        public virtual DbSet<ADDROBJ78> ADDROBJ78 { get; set; }
        public virtual DbSet<ADDROBJ79> ADDROBJ79 { get; set; }
        public virtual DbSet<ADDROBJ83> ADDROBJ83 { get; set; }
        public virtual DbSet<ADDROBJ86> ADDROBJ86 { get; set; }
        public virtual DbSet<ADDROBJ87> ADDROBJ87 { get; set; }
        public virtual DbSet<ADDROBJ89> ADDROBJ89 { get; set; }
        public virtual DbSet<ADDROBJ91> ADDROBJ91 { get; set; }
        public virtual DbSet<ADDROBJ92> ADDROBJ92 { get; set; }
        public virtual DbSet<ADDROBJ99> ADDROBJ99 { get; set; }
        public virtual DbSet<HOUSE61> HOUSE61 { get; set; }
    }
}
